Resendiz_Willy_HW3/Resendiz_Willy_HW3/Controllers/SeedController.cs
//TODO: Change this using statement to match your project (LastName_FirstName_HW3)
using Resendiz_Willy_HW3.DAL;
using Microsoft.AspNetCore.Mvc;


//TODO: Update this namespace to match your project's name
namespace Resendiz_Willy_HW3.Controllers
{
    public class SeedController : Controller
    {
        private AppDbContext _db;

        public SeedController(AppDbContext context)
        {
            _db = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SeedLanguages()
        {
            try
            {
                Seeding.SeedLanguages.SeedAllLanguages(_db);
            }
            catch (Exception ex)
            {
                //create a new list to hold all the errors
                List<String> errors = new List<String>();

                //add a generic message
                errors.Add("There was an error adding genres to the database!");
                
                //add the message from the exception
                errors.Add(ex.Message);

                //add messages from inner exceptions (if there are any)
                if (ex.InnerException != null)
                { 
                    errors.Add(ex.InnerException.Message);
                    if (ex.InnerException.InnerException != null)
                    {
                        errors.Add(ex.InnerException.InnerException.Message);
                        if (ex.InnerException.InnerException.InnerException != null)
                        {
                            errors.Add(ex.InnerException.InnerException.InnerException.Message);
                        }
                    }
                }
                
                //return the error message with the list of errors
                return View("Error", errors );
            }

            //everything is okay - return the confirmation page
            return View("Confirm");
        }

        public IActionResult SeedRepositories()
        {
            try
            {
               Seeding.SeedRepositories.SeedAllRepositories(_db);
            }
            catch (Exception ex)
            {
                //create a new list for the error messages
                List<String> errors = new List<String>();

                //add a generic error message
                errors.Add("There was a problem adding repositories to the database");
                
                //add message from the exception
                errors.Add(ex.Message);

                //add messages from inner exceptions, if there are any
                if (ex.InnerException != null)
                {
                    errors.Add(ex.InnerException.Message);
                    if (ex.InnerException.InnerException != null)
                    {
                        errors.Add(ex.InnerException.InnerException.Message);
                        if (ex.InnerException.InnerException.InnerException != null)
                        {
                            errors.Add(ex.InnerException.InnerException.InnerException.Message);
                        }
                    }
                }

                //return the error view with the errors
                return View("Error", errors);
            }

            //everything is okay - return the confirmation page
            return View("Confirm");
        }
    }
}

Resendiz_Willy_HW3/Resendiz_Willy_HW3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <!--This is the code for the navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">

            <!--This is the code for the "hamburger menu" button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--This is the link to the home page - you can leave this as is -->
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>

            <!--everything in this section will collapse when the screen is small -->
            <div class="collapse navbar-collapse" id="nav-content">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!--TODO: Products is included here as an example, but you will need to edit this link and add more -->
                    <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                    <li class="nav-item"><a asp-controller="Seed" asp-action="Index" class="nav-link">Seeding</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>